server:
  port: 8003
  tomcat:
    max-connections: 300
    max-threads: 1000
spring:
  datasource:
    basedt:
      name: baseDt
      url: jdbc:mysql://localhost:3306/pd_dev_v5.0.0?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: developer
      password: test@123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    seconddt:
      name: secondDt
      url: jdbc:mysql://localhost:3306/pd_test_v5.0.0?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: developer
      password: test@123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

